// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SetPoint.DAL._2.Context;

#nullable disable

namespace SetPoint.DAL.Migrations
{
    [DbContext(typeof(SetPointDbContext))]
    [Migration("20260702071438_AddUpdatedAtAndUserCompositeIndexes")]
    partial class AddUpdatedAtAndUserCompositeIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SetPoint.DAL._1.Entity.BodyMeasurements", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<double?>("BodyWater")
                        .HasColumnType("double precision")
                        .HasColumnName("BODY_WATER")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATE")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<double?>("FatMass")
                        .HasColumnType("double precision")
                        .HasColumnName("FAT_MASS")
                        .HasColumnOrder(10);

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_USER")
                        .HasColumnOrder(6);

                    b.Property<double?>("MuscleMass")
                        .HasColumnType("double precision")
                        .HasColumnName("MUSCLE_MASS")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("WEIGHT")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("IdUser", "UpdatedAt");

                    b.ToTable("BODY_MEASUREMENTS");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnOrder(7);

                    b.Property<string>("EquipmentType")
                        .HasColumnType("text")
                        .HasColumnName("EQUIPMENT_TYPE")
                        .HasColumnOrder(9);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("IMAGE_URL")
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("EXERCISE");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.ExerciseMuscleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("EXERCISE_ID")
                        .HasColumnOrder(6);

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid")
                        .HasColumnName("MUSCLE_GROUP_ID")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MuscleId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("EXERCISE_MUSCLE_GROUP");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.ExerciseSets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("REPS")
                        .HasColumnOrder(8);

                    b.Property<double?>("Rpe")
                        .HasColumnType("double precision")
                        .HasColumnName("RPE")
                        .HasColumnOrder(10);

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("SET_NUMBER")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("WEIGHT")
                        .HasColumnOrder(9);

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("WORKOUT_EXERCISE_ID")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("EXERCISE_SETS");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.FeedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<string>("CustomText")
                        .HasColumnType("text")
                        .HasColumnName("CUSTOM_TEXT")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("EVENT_TYPE")
                        .HasColumnOrder(6);

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("EXERCISE_ID")
                        .HasColumnOrder(7);

                    b.Property<double?>("MetricValue")
                        .HasColumnType("double precision")
                        .HasColumnName("METRIC_VALUE")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("FEED_EVENTS");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.Logs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("TYPE")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("LOGS");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.MuscleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnOrder(7);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("MUSCLE_GROUP");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.RoutineExercises", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("EXERCISE_ID")
                        .HasColumnOrder(7);

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("SORT_ORDER")
                        .HasColumnOrder(8);

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("REPS")
                        .HasColumnOrder(10);

                    b.Property<int>("RestSecond")
                        .HasColumnType("integer")
                        .HasColumnName("REST_SECOND")
                        .HasColumnOrder(12);

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid")
                        .HasColumnName("ROUTINE_ID")
                        .HasColumnOrder(6);

                    b.Property<int>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("SETS")
                        .HasColumnOrder(9);

                    b.Property<double?>("TargetWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("TARGET_WEIGHT")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("RoutineId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("ROUTINE_Exercises");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.RoutineRequests", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("RECEIVER_ID")
                        .HasColumnOrder(6);

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid")
                        .HasColumnName("ROUTINE_ID")
                        .HasColumnOrder(7);

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("SENDER_ID")
                        .HasColumnOrder(5);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ReceiverId", "UpdatedAt");

                    b.HasIndex("SenderId", "UpdatedAt");

                    b.ToTable("ROUTINE_REQUESTS");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.Routines", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("ROUTINES");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("BIRTH_DATE")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EMAIL")
                        .HasColumnOrder(6);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME")
                        .HasColumnOrder(8);

                    b.Property<double?>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("HEIGHT")
                        .HasColumnOrder(11);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PASSWORD_HASH")
                        .HasColumnOrder(7);

                    b.Property<int?>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("SEX")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.UsersInvitations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EMAIL")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EXPIRES_AT")
                        .HasColumnOrder(8);

                    b.Property<bool>("Sended")
                        .HasColumnType("boolean")
                        .HasColumnName("SENDED")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("SENDER_USER_ID")
                        .HasColumnOrder(7);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS")
                        .HasColumnOrder(9);

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("TOKEN")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("USER_INVITATIONS");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.UsersRelations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid")
                        .HasColumnName("FRIEND_ID")
                        .HasColumnOrder(6);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("FriendId", "UpdatedAt");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("USERS_RELATIONS");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.WorkoutExercises", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("EXERCISE_ID")
                        .HasColumnOrder(7);

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("SORT_ORDER")
                        .HasColumnOrder(8);

                    b.Property<int>("RestSecond")
                        .HasColumnType("integer")
                        .HasColumnName("REST_SECOND")
                        .HasColumnOrder(9);

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("SESSION_ID")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("WORKOUT_EXERCISES");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.WorkoutSessions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_AT")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATE")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DELETED_AT")
                        .HasColumnOrder(4);

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("DURATION")
                        .HasColumnOrder(8);

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("NOTES")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("WORKOUT_SESSIONS");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.BodyMeasurements", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Users", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetPoint.DAL._1.Entity.MuscleGroup", "MuscleGroup")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.ExerciseSets", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.WorkoutExercises", "WorkoutExercise")
                        .WithMany()
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.FeedEvent", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId");

                    b.HasOne("SetPoint.DAL._1.Entity.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.Logs", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.RoutineExercises", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetPoint.DAL._1.Entity.Routines", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.RoutineRequests", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Users", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetPoint.DAL._1.Entity.Routines", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetPoint.DAL._1.Entity.Users", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Routine");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.Routines", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.UsersInvitations", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Users", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.UsersRelations", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Users", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetPoint.DAL._1.Entity.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.WorkoutExercises", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetPoint.DAL._1.Entity.WorkoutSessions", "WorkoutSession")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("SetPoint.DAL._1.Entity.WorkoutSessions", b =>
                {
                    b.HasOne("SetPoint.DAL._1.Entity.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
